Select RFC, NOMBRE, APELLIDOP, APELLIDOM, FECHADENACIMIENTO, FKTIPOPERSONAL from checador.personal
USE checador;

insert into `personal`(`RFC`,`NOMBRE`,`APELLIDOP`,`APELLIDOM`,`FECHADENACIMIENTO`,`FKTIPOPERSONAL`) values ('BACD970929UB3','Diego','Baca','Casillas','28/07/2020 0:00:00',2);
insert into `personal`(`RFC`,`NOMBRE`,`APELLIDOP`,`APELLIDOM`,`FECHADENACIMIENTO`,`FKTIPOPERSONAL`) values ('MEBD990816HM5','Daniela','Mejia','Barrera','16/08/1999 0:00:00',1);
insert into `personal`(`RFC`,`NOMBRE`,`APELLIDOP`,`APELLIDOM`,`FECHADENACIMIENTO`,`FKTIPOPERSONAL`) values ('PENF000526AM9','Fátima','Pedroza','Noriega','26/05/2000 0:00:00',3);
